routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UmkmController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UmkmMakassarController;
use App\Http\Controllers\UmkmGowaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

// Form Makassar
Route::get('/form-makassar', function () {
  return view('pages.form-mks');
});
Route::post('addForm-Makassar', [UmkmMakassarController::class, 'store'])->name('addForm-Makassar');

// Form Gowa
Route::get('/form-gowa', function () {
    return view('pages.form-gowa');
});
Route::post('addForm-Gowa', [UmkmGowaController::class, 'store'])->name('addForm-Gowa');

// Form Cek
Route::post('search', [UmkmController::class, 'search'])->name('search');
Route::put('editSearch/{id}', [UmkmController::class, 'update'])->name('editSearch');

// Form Erro
Route::get('/form-error', function () {
  return view('pages.form-error');
});

// Profile
Route::put('editProfile/{id}', [UserController::class, 'update'])->name('editProfile');
Route::put('editPassword/{id}', [UserController::class, 'changePassword'])->name('editPassword');
// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::resource('dashboard', DashboardController::class);
});

Route::middleware(['auth', 'checkRole:Admin'])->group(function () {
    Route::resource('data-umkm', UmkmController::class);
    Route::resource('user', UserController::class);
    Route::get('export-users', [UserController::class, 'export'])->name('export-users');
    Route::get('export-umkm', [UmkmController::class, 'export'])->name('export-umkm');
});

Route::middleware(['auth', 'checkRole:Admin,Kota Makassar'])->group(function () {
    Route::resource('umkm-makassar', UmkmMakassarController::class);
    Route::get('export-makassar', [UmkmMakassarController::class, 'export'])->name('export-makassar');
});

Route::middleware(['auth', 'checkRole:Admin,Kabupaten Gowa'])->group(function () {
    Route::resource('umkm-gowa', UmkmGowaController::class);
    Route::get('export-gowa', [UmkmGowaController::class, 'export'])->name('export-gowa');
});

resources/views/includes/admin/footer.blade.php
					<div class="row">
                        <div class="col-md-12">
                            <span class="footer-text">2020 © KKN 105 UNHAS</span>
                        </div>
                    </div>

resources/views/includes/admin/script.blade.php
        <!-- Javascripts -->
        <script src="{{asset('admin/plugins/jquery/jquery-3.4.1.min.js')}}"></script>
        <script src="{{asset('admin/plugins/bootstrap/popper.min.js')}}"></script>
        <script src="{{asset('admin/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
        <script src="{{asset('admin/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>

        <script src="{{asset('admin/plugins/DataTables/datatables.min.js')}}"></script>
        <script src="{{asset('admin/js/connect.min.js')}}"></script>
        <script src="{{asset('admin/js/pages/datatables.js')}}"></script>
        <script src="{{asset('vendor/sweetalert/sweetalert.all.js')}}"></script>

resources/views/includes/admin/sidebar.blade.php
            <div class="logo-box"><a href="/" class="logo-text">ADMIN</a><a href="#" id="sidebar-close"><i class="material-icons">close</i></a> <a href="#" id="sidebar-state"><i class="material-icons">adjust</i><i class="material-icons compact-sidebar-icon">panorama_fish_eye</i></a></div>
                <div class="page-sidebar-inner slimscroll">
                    <ul class="accordion-menu">
                        <!-- <li class="sidebar-title">
                            Apps
                        </li> -->
                        <li class="{{ (request()->routeIs('dashboard.*')) ? 'active-page' : '' }}">
                            <a href="{{ route('dashboard.index') }}" class="active"><i class="material-icons-outlined">dashboard</i>Dashboard</a>
                        </li>
                        <li class="{{ (request()->routeIs('data-umkm.*')) || (request()->routeIs('user.*')) ? 'active-page' : '' }}">
                            <a href="#"><i class="material-icons-outlined">sticky_note_2</i>Master Data<i class="material-icons has-sub-menu">add</i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="{{ route('data-umkm.index') }}" class="{{ (request()->routeIs('data-umkm.*')) ? 'active' : '' }}">Data UMKM</a>
                                </li>
                                <li>
                                    <a href="{{ route('user.index') }}" class="{{(request()->routeIs('user.*')) ? 'active' : '' }}">Users</a>
                                </li>
                            </ul>
                        </li>
                        <li class="{{(request()->routeIs('umkm-makassar.*')) ? 'active-page' : '' }}">
                            <a href="{{ route('umkm-makassar.index') }}" class="active"><i class="material-icons-outlined">store</i>UMKM Kota Makassar</a>
                        </li>
                        <li class="{{(request()->routeIs('umkm-gowa.*')) ? 'active-page' : '' }}">
                            <a href="{{ route('umkm-gowa.index') }}" class="active"><i class="material-icons-outlined">store</i>UMKM Kabupaten Gowa</a>
                        </li>
                    </ul>
                </div>

resources/views/includes/admin/style.blade.php
        <!-- Styles -->
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
        <link href="{{asset('admin/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
        <link href="{{asset('admin/plugins/font-awesome/css/all.min.css')}}" rel="stylesheet">
        <link href="{{asset('admin/plugins/DataTables/datatables.min.css')}}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

      
        <!-- Theme Styles -->
        <link href="{{asset('admin/css/connect.min.css')}}" rel="stylesheet">
        <link href="{{asset('admin/css/dark_theme.css')}}" rel="stylesheet">
        <link href="{{asset('admin/css/custom.css')}}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->