routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UmkmController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UmkmMakassarController;
use App\Http\Controllers\UmkmGowaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

// Form Makassar
Route::get('/form-makassar', function () {
  return view('pages.form-mks');
});
Route::post('addForm-Makassar', [UmkmMakassarController::class, 'store'])->name('addForm-Makassar');

// Form Gowa
Route::get('/form-gowa', function () {
    return view('pages.form-gowa');
});
Route::post('addForm-Gowa', [UmkmGowaController::class, 'store'])->name('addForm-Gowa');

// Form Cek
Route::post('search', [UmkmController::class, 'search'])->name('search');
Route::put('editSearch/{id}', [UmkmController::class, 'update'])->name('editSearch');

// Form Erro
Route::get('/form-error', function () {
  return view('pages.form-error');
});

// Profile
Route::put('editProfile/{id}', [UserController::class, 'update'])->name('editProfile');
Route::put('editPassword/{id}', [UserController::class, 'changePassword'])->name('editPassword');
// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::resource('dashboard', DashboardController::class);
});

Route::middleware(['auth', 'checkRole:Admin'])->group(function () {
    Route::resource('data-umkm', UmkmController::class);
    Route::resource('user', UserController::class);
    Route::get('export-users', [UserController::class, 'export'])->name('export-users');
    Route::get('export-umkm', [UmkmController::class, 'export'])->name('export-umkm');
});

Route::middleware(['auth', 'checkRole:Admin,Kota Makassar'])->group(function () {
    Route::resource('umkm-makassar', UmkmMakassarController::class);
    Route::get('export-makassar', [UmkmMakassarController::class, 'export'])->name('export-makassar');
});

Route::middleware(['auth', 'checkRole:Admin,Kabupaten Gowa'])->group(function () {
    Route::resource('umkm-gowa', UmkmGowaController::class);
    Route::get('export-gowa', [UmkmGowaController::class, 'export'])->name('export-gowa');
});

resources/views/pages/form-error.blade.php
@extends('layouts.master-form')
@section('content')

@push('addon-style')
<style>
      /* Split the screen in half */
.split {
  height: 100%;
  width: 50%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  padding-top: 20px;
}

/* Control the left side */
.left {
  left: 0;
  background-color: #111;
}

/* Control the right side */
.right {
  right: 0;
  background-color: red;
}

/* If you want the content centered horizontally and vertically */
.centered {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

/* Style the image inside the centered container, if needed */
.centered img {
  width: 150px;
  border-radius: 50%;
}
</style>
@endpush

<div class="img-holder">
    <div class="bg"></div>
    <div class="info-holder simple-info">
        <div><h3>Pemetaan Dampak Covid-19 Terhadap Ekonomi UMKM</h3></div>
    </div>
</div>
<div class="form-holder">
    <div class="form-content">
        <div class="section" id="section1">

                <section class="content-inside-section">

                    <div class="container">

                        <div class="container-inside">

                            <div class="main-content">

                               <div class="split left">
                                    <img src="{{asset('home/img/404.png')}}" style="width: 50%; height: 50%">
                                    </div>

                                <span class="col-md-9">
                                <div class="split right">
                                <h2>Maaf data yang anda cari tidak ditemukan!</h2>
                                <a id="button" href="/#Home">Kembali</a>
                                </div>
                                </span>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
    </div>
    
</div>

@endsection

resources/views/pages/home.blade.php
<!DOCTYPE html>
<html lang="zxx" class="no-js">

	<head>
		<meta charset="utf-8">
		<title>Pemetaan Dampak Covid-19</title>
		<meta name="description" content="dampak umkm, kkn 105 unhas, unhas, kkn 105, Covid-19">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Madeon08">

        <!-- ================= Favicons ================== -->
        <!-- Standard -->
        <link rel="shortcut icon" href="{{asset('home/img/Logo_UH.png')}}">
		<!-- ============== Resources style ============== -->
		<link rel="stylesheet" type="text/css" href="{{asset('home/css/style.css')}}" />

		<!-- Modernizr runs quickly on page load to detect features -->
		<script src="{{asset('home/js/modernizr.custom.js')}}"></script>
	</head>

	<body>

		<!-- *** LOADING *** -->

		<div id="loading">

			<div class="loader">
				<span class="dots">	.</span>
				<span class="dots">	.</span>
				<span class="dots">	.</span>
				<span class="dots">	.</span>
				<span class="dots">	.</span>
				<span class="dots">	.</span>
				<p class="loader__label"><span data-words="Memuat data"></span></p>
			</div>
		</div>

		<!-- *** / LOADING *** -->

		<!-- *** Menu icon for opening/closing the menu on small screen *** -->

		<button id="small-screen-menu">

			<span class="custom-menu"></span>

		</button>

		<!-- *** / Menu icon *** -->

		<!-- *** Constellation *** -->
		<canvas id="constellationel"></canvas> <!-- Canvas displaying the animation -->

		<div id="constellation"></div> <!-- Used to display your background picture, set up the path to your picture in your css/style.css file OR replace the img/constellation.jpg file by yours -->

		<!-- The overlay that you can see over the animation is generated with the following CSS rule : .custom-overlay, it can be found in your style.css file under 2. GENERIC STYLES part -->
		<div class="custom-overlay"></div>		<!-- Logo on top right -->
		<a class="brand-logo" href="#Home">
			<img src="{{asset('home/img/Logo_UH.png')}}" alt="Our company logo" class="img-fluid" />
		</a>

		<!-- *** Fullpage sections *** -->
		<div id="fullpage">

			<!-- +++ START - Home +++ -->
			<div class="section" id="section0">

				<section class="content-inside-section">

					<div class="container">

						<div class="container-inside">

							<div class="main-content align-center">

								<!-- *** TEXT TITLE *** -->
								<h1>
									Pemetaan Dampak Covid-19 Terhadap Ekonomi UMKM
								</h1>

								<!-- *** COUNTDOWN TITLE *** -->
								<!-- Set your date at the bottom of js/jquery.countdown.js -->

								<!-- <h1>
									official launch in<br>
									<span id="getting-started"></span>
								</h1> -->

								<p class="on-home">Situs ini adalah bagian dari program kerja KKN Gelombang 105 Unhas yang bertujuan untuk <br> mengidentifikasi dampak covid-19 terhadap ekonomi UMKM di Kota Makassar dan Kabupaten Gowa
								</p>

								<br>

								<div class="command">

									<!-- ********** IF YOU WANT TO USE MORE POPUPS, SEE THE RECOMMENDATIONS AT THE END OF js/dialogFx.js ********** -->

									<a id="button-more" class="light-btn" href="#Form">Isi Form
										<span class="ask-to-scroll">
											<span class="arrow"><span></span><span></span></span>
											<span class="arrow"><span></span><span></span></span>
											<span class="arrow"><span></span><span></span></span>
										</span>
									</a>

									<div class="clear"></div>

								</div>
							</div>
						</div>
					</div>
				</section>

			</div>
			<!-- +++ END - Home +++ -->

			<!-- +++ START - Form +++ -->
			<div class="section" id="section1">

				<section class="content-inside-section">

					<div class="container">

						<div class="container-inside">

							<div class="main-content">

								<h2>Form Pengisian Dampak Covid-19 Untuk UMKM</h2>

								<span class="separator"></span>

								<div class=" command row justify-content-center">
									<a id="button" class="light-btn colored" href="/form-makassar">Form Untuk Kota Makassar</a>
									<a id="button" class="light-btn colored" href="/form-gowa">Form Untuk Kabupaten Gowa</a>
									<form action="{{ route('search') }}" method="POST">
									@csrf
									<div class="search input-group mb-3">
    									<input type="text" name="key" class="form-control" placeholder="Masukkan NIK" style="font-size: 2rem">
    								<div class="input-group-append">
      								<button class="submit" type="submit">
      									<i class="fa fa-search"></i>
      								</button>  
     								</div>
     								</form>
  								</div>
								</div>
								
							</div>
						</div>
					</div>
				</section>

			</div>
			<!-- +++ END - About +++ -->



		</div>
		<!-- +++ / Fullpage sections +++ -->

		<!-- START - Newsletter Popup -->
		<div id="somedialog_1" class="dialog">

			<div class="dialog__overlay"></div>
					
			<div class="dialog__content">
						
				<div class="dialog-inner">
							
					<h3>You like taking the lead of line?</h3>
							
					<p>Being the first to know always feels great... Signing up to our newsletter gives you <strong>exclusive access to our Grand Opening!</strong></p>

					<!-- Newsletter Form -->
					<div id="subscribe">

		                <form action="php/notify-me.php" id="notifyMe" method="POST">

		                    <div class="form-group">

		                        <div class="controls">
		                            
		                        	<!-- Field  -->
		                        	<input type="text" id="mail-sub" name="email" placeholder="Click here to type your email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Click here to type your email'" class="form-control email srequiredField" />

		                            <!-- Button -->
		                            <button class="btn btn-lg submit on-center"><span>Get notified</span></button>

		                            <div class="clear"></div>

		                        </div>
		                    </div>
		                </form>
        			</div>
        			<!-- /. Newsletter Form -->

				</div>

				<!-- Cross closing the Newsletter Popup -->
				<button class="close-newsletter" data-dialog-close><i class="icon ion-close-round"></i></button>

			</div>		
		</div>
		<!-- END - Newsletter Popup -->

		<!-- CONTACT FORM - Answer for the contact form is displayed in the next div, do not remove it. -->       
        <div id="block-answer" class="">

            <div id="answer"></div>

        </div>

		<!-- NEWSLETTER FORM - Answer for the newsletter form is displayed in the next div, do not remove it. -->
		<div class="block-message">

			<div class="message">

				<p class="notify-valid"></p>
			</div>
		</div>

		<footer>

			<div class="line"></div>

			<div class="row">

				<div class="col-12 col-xl-4 footer-nav">

					<ul id="bottomMenu" class="on-left">

						<li data-menuanchor="Home" class="active">
							<a href="#Home">Home</a>
						</li>

						<li data-menuanchor="Form">
							<a href="#Form">Isi Form</a>
						</li>
					</ul>
				</div>

				<div class="col-12 col-xl-4 footer-copyright">
					<p>KKN 105 UNIVERSITAS HASANUDDIN</p>
				</div>
			</div>
		</footer>

		<!-- ///////////////////\\\\\\\\\\\\\\\\\\\ -->
        <!-- ********** jQuery Resources ********** -->
        <!-- \\\\\\\\\\\\\\\\\\\/////////////////// -->

        <!-- * Libraries jQuery, Easing and Bootstrap - Be careful to not remove them * -->
        <script src="{{asset('home/js/jquery.min.js')}}"></script>
        <script src="{{asset('home/js/jquery.easings.min.js')}}"></script>
        <script src="{{asset('home/js/bootstrap.min.js')}}"></script>

		<!-- Countdown plugin -->
		<script src="{{asset('home/js/jquery.countdown.js')}}"></script>

		<!-- FullPage plugin -->
		<script src="{{asset('home/js/jquery.fullPage.js')}}"></script>

		<!-- Constellation plugin -->
		<script src="{{asset('home/js/constellation.js')}}"></script>

		<!-- Popup Newsletter Form -->
		<script src="{{asset('home/js/classie.js')}}"></script>
		<script src="{{asset('home/js/dialogFx.js')}}"></script>

		<!-- Newsletter plugin -->
		<script src="{{asset('home/js/notifyMe.js')}}"></script>

		<!-- Gallery plugin -->
		<script src="{{asset('home/js/jquery.detect_swipe.min.js')}}"></script>
		<script src="{{asset('home/js/featherlight.js')}}"></script> 
		<script src="{{asset('home/js/featherlight.gallery.js')}}"></script>

		<!-- Main JS File -->
		<script src="{{asset('home/js/main.js')}}"></script>

	</body>

</html>

resources/views/pages/show-umkm.blade.php
@extends('layouts.master-admin')
@section('content')

 <div class="row">
    <div class="col-xl">
        <div class="card">
            <div class="card-body">
                @foreach($data_umkm as $data)
                <h3>Detail Data Dampak Covid-19 Terhadap Ekonomi UMKM</h3>
                @if($pages == 'Admin')
                <?php 
                    $link = 'data-umkm.destroy';
                    $loc  = 'data-umkm.index';
                ?>
                @elseif($pages == 'Makassar')
                <?php 
                    $link = 'umkm-makassar.destroy';
                    $loc  = 'umkm-makassar.index';
                ?>
                @elseif($pages == 'Gowa')
                <?php 
                    $link = 'umkm-gowa.destroy';
                    $loc  = 'umkm-gowa.index';
                ?>
                @endif
                    <button type="button" class="btn btn-danger btn-xs deleteumkm" data-id="{{$data->id}}" data-loc="{{ route($loc)}}" data-url="{{ route($link, $data->id) }}" style="float: right; margin-top: -25px;">
                        <i class="material-icons-outlined" style="vertical-align: middle;">delete</i>
                    </button>
                @if($pages == 'Admin')
                <a href="{{ route('data-umkm.edit', $data->id) }}">
                @elseif($pages == 'Makassar')
                <a href="{{ route('umkm-makassar.edit', $data->id) }}">
                @elseif($pages == 'Gowa')
                <a href="{{ route('umkm-gowa.edit', $data->id) }}">
                @endif
                    <button type="button" class="btn btn-warning btn-xs" style="float: right; margin-top: -25px; margin-right: 10px;">
                        <i class="material-icons-outlined" style="vertical-align: middle;">create</i>
                    </button>
                </a>
            <div class="form-group">
            <div class="form-content">
            <div class="form-items">
                <meta name="csrf-token-delete" content="{{ csrf_token() }}">
                <div class="form-group">
                    <div class="col-12">
                        <label>NIK</label>
                        <input type="text" class="form-control" id="nik" name="nik" value="{{$data->nik}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Nama</label>
                        <input type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Nama Usaha Mikro Kecil dan Menengah (UMKM)</label>
                        <input type="text" class="form-control" id="nama_umkm" name="nama_umkm" value="{{$data->nama_umkm}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>No. Telpon</label>
                        <input type="text" id="no_tlp" name="nomor" class="form-control" value="{{$data->no_tlp}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Kategori</label>
                        <input type="text" id="kategori" name="kategori" class="form-control" value="{{$data->kategori}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Kabupaten/Kota</label>
                        <input type="text" id="kab_kota" name="kab_kota" class="form-control" value="{{$data->kab_kota}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Alamat Lengkap</label>
                        <input type="text" id="alamat" name="alamat" value="{{$data->alamat}}" class="form-control" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Permasalahan</label>
                        <textarea id="permasalahan" name="permasalahan" class="form-control" disabled>{{$data->permasalahan}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Solusi Yang Dibutuhkan</label>
                        <textarea id="solusi" name="solusi" class="form-control" disabled>{{$data->solusi}}</textarea>
                    </div>
                </div>
                <br>
                <h5 class="text-center" style="color: #5fd0a5">Sebelum Pandemi Covid-19</h5>
                <div class="form-group">
                <div class="row">
                    <div class="col-sm">
                        <label>Aset</label>
                        <input type="text" id="aset_before" name="nomor" class="form-control" value="{{$data->aset_before}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Omzet</label>
                        <input type="text" id="omzet_before" name="nomor" class="form-control" value="{{$data->omzet_before}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Tenaga Kerja</label>
                        <input type="text" id="tenaga_kerja_before" name="nomor" class="form-control" value="{{$data->tenaga_kerja_before}}" disabled>
                    </div>
                </div>
                </div>
                <div class="form-group">
                <div class="row">
                    <div class="col-sm">
                        <label>Jenis Bahan Baku</label>
                        <input type="text" id="bahan_baku_before" name="bahan_baku_before" class="form-control" value="{{$data->bahan_baku_before}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Volume</label>
                        <input type="text" id="volume_before" name="nomor" class="form-control" value="{{$data->volume_before}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Satuan Bahan Baku</label>
                        <input type="text" id="satuan_baku_before" name="satuan_baku_before" class="form-control" value="{{$data->satuan_baku_before}}" disabled>
                    </div>
                </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Hutang</label>
                        <input type="text" id="hutang_before" name="nomor" class="form-control" value="{{$data->hutang_before}}" disabled>
                    </div>
                </div>
                <br>
                <h5 class="text-center" style="color: #5fd0a5">Pada Saat Pandemi Covid-19</h5>
                <div class="form-group">
                <div class="row">
                    <div class="col-sm">
                        <label>Aset</label>
                        <input type="text" id="aset_after" name="nomor" class="form-control" value="{{$data->aset_after}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Omzet</label>
                        <input type="text" id="omzet_after" name="nomor" class="form-control" value="{{$data->omzet_after}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Tenaga Kerja</label>
                        <input type="text" id="tenaga_kerja_after" name="nomor" class="form-control" value="{{$data->tenaga_kerja_after}}" disabled>
                    </div>
                </div>
                </div>
                <div class="form-group">
                <div class="row">
                    <div class="col-sm">
                        <label>Jenis Bahan Baku</label>
                        <input type="text" id="bahan_baku_after" name="bahan_baku_after" class="form-control" value="{{$data->bahan_baku_after}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Volume</label>
                        <input type="text" id="volume_after" name="nomor" class="form-control" value="{{$data->volume_after}}" disabled>
                    </div>
                    <div class="col-sm">
                        <label>Satuan Bahan Baku</label>
                        <input type="text" id="satuan_baku_after" name="satuan_baku_after" class="form-control" value="{{$data->satuan_baku_after}}" disabled>
                    </div>
                </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label>Hutang</label>
                        <input type="text" id="hutang_after" name="nomor" class="form-control" value="{{$data->hutang_after}}" disabled>
                    </div>
                </div>
                <br>
                <br>
                @endforeach
        </div>
    </div>
</div>

@endsection

@push('addon-script')
<script> 
$(document).ready(function() {
    $('.deleteumkm').click(function(e){
        e.preventDefault();
        var id = $(this).data('id');
        var url = $(this).data('url');
        var loc = $(this).data('loc');
        console.log(loc);
        Swal.fire({
            title: 'Apa Anda Yakin?',
            text: "Anda Tidak Dapat Membatalkan Operasi Ini!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes'
            }).then((result) => {
            if (result.isConfirmed) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token-delete"]').attr('content')
                    }
                });
                $.ajax({
                    url:url,
                    data:{id:id},
                    method:'DELETE',
                    success:function(data){
                    Swal.fire(
                        'Dihapus!',
                        'Data UMKM Berhasil Dihapus.',
                        'success'
                    )
                    setTimeout(function(){
                    window.location = loc;
                    }, 1000);
                    }
                });
            }
            })
    });
});

</script> 
@endpush

resources/views/pages/umkm.blade.php
@extends('layouts.master-admin')
@section('content')
                    <div class="page-info">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{$nav}}</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{$sub_nav}}</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="main-wrapper">
                        <div class="row">
                            <div class="col">
                                <div class="card">
                                    <div class="card-body">
                                        <a href="javascript:void(0);" class="dropdown float-right" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="margin-top: 10px">
                                            <i class="material-icons">more_vert</i>
                                        </a>
                                        <ul class="dropdown-menu pull-right">
                                            <li style="padding: 7px 18px;">
                                                @if($pages == 'Admin')
                                                <a href="{{ route('data-umkm.create') }}">Tambah Data UMKM</a>
                                                @elseif($pages == 'Makassar')
                                                <a href="{{ route('umkm-makassar.create') }}">Tambah Data UMKM</a>
                                                @elseif($pages == 'Gowa')
                                                <a href="{{ route('umkm-gowa.create') }}">Tambah Data UMKM</a>
                                                @endif
                                            </li>
                                             <li style="padding: 7px 18px;">
                                                @if($pages == 'Admin')
                                                <a href="{{ route('export-umkm') }}">Download Data</a>
                                                @elseif($pages == 'Makassar')
                                                <a href="{{ route('export-makassar') }}">Download Data</a>
                                                @elseif($pages == 'Gowa')
                                                <a href="{{ route('export-gowa') }}">Download Data</a>
                                                @endif
                                            </li>
                                        </ul>
                                        <table id="zero-conf" class="display" style="width:100%">
                                            <meta name="csrf-token-delete" content="{{ csrf_token() }}">
                                            <thead>
                                                <tr>
                                                    <th>NIK</th>
                                                    <th>Nama UMKM</th>
                                                    <th>Alamat</th>
                                                    <th>Jenis UMKM</th>
                                                    @if(request()->routeIs('data-umkm.*'))
                                                    <th>Kabupaten / Kota</th>
                                                    @endif
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($data_umkm as $data)
                                                <tr>
                                                    <td>{{$data->nik}}</td>
                                                    <td>{{$data->nama_umkm}}</td>
                                                    <td>{{$data->alamat}}</td>
                                                    <td>{{$data->kategori}}</td>
                                                    @if(request()->routeIs('data-umkm.*'))
                                                    <td>{{$data->kab_kota}}</td>
                                                    @endif
                                                    <td>
                                                        @if($pages == 'Admin')
                                                        <a href="{{ route('data-umkm.show', $data->id) }}">
                                                        @elseif($pages == 'Makassar')
                                                        <a href="{{ route('umkm-makassar.show', $data->id) }}">
                                                        @elseif($pages == 'Gowa')
                                                        <a href="{{ route('umkm-gowa.show', $data->id) }}">
                                                        @endif 
                                                            <button type="button" class="btn btn-info btn-xs" style="height: 30px; width: 30px">
                                                                <i class="material-icons-outlined" style="vertical-align: middle; font-size: 18px">chrome_reader_mode</i>
                                                            </button>
                                                        </a>
                                                    </td>
                                                </tr>
                                                @endforeach
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
@endsection